apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: swagger-bilderlings-eu-tls
spec:
  secretName: swagger-bilderlings-eu-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "swagger.minikube.k8s.iamoffice.lv"
  dnsNames:
  - "swagger.minikube.k8s.iamoffice.lv"
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - "swagger.minikube.k8s.iamoffice.lv"

